**Day - 1**

In [ ]:
import numpy as np
import torch
import cv2
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [ ]:
!nvidia-smi

Sat Aug 26 17:40:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
tensor1 = torch.tensor(7)
tensor2 = torch.tensor([1,2])
tensor3 = torch.tensor([[1,2]])
tensor4 = torch.tensor([[4,5],[6,7]])
tensor5 = torch.tensor([[[1,2],[3,4]]])

print(tensor1.ndim,tensor2.ndim,tensor3.ndim,tensor4.ndim,tensor5.ndim)
print(tensor1.shape,tensor2.shape,tensor3.shape,tensor4.shape,tensor5.shape)

0 1 2 2 3
torch.Size([]) torch.Size([2]) torch.Size([1, 2]) torch.Size([2, 2]) torch.Size([1, 2, 2])


In [ ]:
random_tensor = torch.rand((1,3,3))
print(random_tensor.ndim, random_tensor.shape)
print(random_tensor)

3 torch.Size([1, 3, 3])
tensor([[[0.7174, 0.6653, 0.7665],
         [0.1527, 0.9405, 0.6546],
         [0.1113, 0.4606, 0.1823]]])


In [ ]:
zeros = torch.zeros(3,3)
print(zeros.ndim, zeros.shape, zeros.dtype, zeros.device)
print(zeros)

ones = torch.ones(3,3)
print(ones.ndim, ones.shape, ones.dtype, ones.device, ones.requires_grad)
print(ones)

2 torch.Size([3, 3]) torch.float32 cpu
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
2 torch.Size([3, 3]) torch.float32 cpu False
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
tensor_range = torch.range(1,5,0.1)
tensor_arange = torch.arange(2,6,0.5)
print(tensor_range.ndim, tensor_range.shape)
print(tensor_range,"\n")
print(tensor_arange.ndim, tensor_arange.shape)
print(tensor_arange)

1 torch.Size([41])
tensor([1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000,
        1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000, 2.7000,
        2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000,
        3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000, 4.5000,
        4.6000, 4.7000, 4.8000, 4.9000, 5.0000]) 

1 torch.Size([8])
tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000])


<ipython-input-7-5d044ec82c3b>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor_range = torch.range(1,5,0.1)


In [ ]:
tens_wo_shape = torch.zeros_like(tensor_range)
tens_wo_shape_arange = torch.ones_like(tensor_arange)
print(tensor_range.shape, tens_wo_shape.shape,"\n")
print(tensor_arange.shape, tens_wo_shape_arange.shape)

torch.Size([41]) torch.Size([41]) 

torch.Size([8]) torch.Size([8])


In [ ]:
print(f"Tensor 1 datatype is: {tensor1.dtype}")
tensor1 = tensor1.type(torch.int8)
print(f"Dtype after change is: {tensor1.dtype}")

Tensor 1 datatype is: torch.int64
Dtype after change is: torch.int8


In [ ]:
print(torch.max(tensor1))
print(torch.min(tensor1))
print(torch.mean(tensor_range))
print(torch.sum(tensor1))

tensor(7, dtype=torch.int8)
tensor(7, dtype=torch.int8)
tensor(3.)
tensor(7)


In [ ]:
print(f"Tensor range is on device: {tensor_range.device}\nAnd the type is: {type(tensor_range)}")
print(f"Now the device is: {tensor_range.to('cuda').device}")
print(f"Putting it back on cpu: {tensor_range.cpu().device}")
print(f"Converting to a numpy ndarray: {type(tensor_range.numpy())}")

Tensor range is on device: cpu
And the type is: <class 'torch.Tensor'>
Now the device is: cuda:0
Putting it back on cpu: cpu
Converting to a numpy ndarray: <class 'numpy.ndarray'>
