**Day - 1**

In [ ]:
import numpy as np
import torch
import cv2
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [ ]:
!nvidia-smi

Sun Aug 27 17:50:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
tensor1 = torch.tensor(7)
tensor2 = torch.tensor([1,2])
tensor3 = torch.tensor([[1,2]])
tensor4 = torch.tensor([[4,5],[6,7]])
tensor5 = torch.tensor([[[1,2],[3,4]]])

print(tensor1.ndim,tensor2.ndim,tensor3.ndim,tensor4.ndim,tensor5.ndim)
print(tensor1.shape,tensor2.shape,tensor3.shape,tensor4.shape,tensor5.shape)

0 1 2 2 3
torch.Size([]) torch.Size([2]) torch.Size([1, 2]) torch.Size([2, 2]) torch.Size([1, 2, 2])


In [ ]:
random_tensor = torch.rand((1,3,3))
print(random_tensor.ndim, random_tensor.shape)
print(random_tensor)

3 torch.Size([1, 3, 3])
tensor([[[0.6487, 0.9613, 0.7772],
         [0.9857, 0.9756, 0.8242],
         [0.6960, 0.5135, 0.3615]]])


In [ ]:
zeros = torch.zeros(3,3)
print(zeros.ndim, zeros.shape, zeros.dtype, zeros.device)
print(zeros)

ones = torch.ones(3,3)
print(ones.ndim, ones.shape, ones.dtype, ones.device, ones.requires_grad)
print(ones)

2 torch.Size([3, 3]) torch.float32 cpu
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
2 torch.Size([3, 3]) torch.float32 cpu False
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
tensor_range = torch.range(1,5,0.1)
tensor_arange = torch.arange(2,6,0.5)
print(tensor_range.ndim, tensor_range.shape)
print(tensor_range,"\n")
print(tensor_arange.ndim, tensor_arange.shape)
print(tensor_arange)

1 torch.Size([41])
tensor([1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000,
        1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000, 2.7000,
        2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000,
        3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000, 4.5000,
        4.6000, 4.7000, 4.8000, 4.9000, 5.0000]) 

1 torch.Size([8])
tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000])


<ipython-input-6-5d044ec82c3b>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor_range = torch.range(1,5,0.1)


In [ ]:
tens_wo_shape = torch.zeros_like(tensor_range)
tens_wo_shape_arange = torch.ones_like(tensor_arange)
print(tensor_range.shape, tens_wo_shape.shape,"\n")
print(tensor_arange.shape, tens_wo_shape_arange.shape)

torch.Size([41]) torch.Size([41]) 

torch.Size([8]) torch.Size([8])


In [ ]:
print(f"Tensor 1 datatype is: {tensor1.dtype}")
tensor1 = tensor1.type(torch.int8)
print(f"Dtype after change is: {tensor1.dtype}")

Tensor 1 datatype is: torch.int64
Dtype after change is: torch.int8


In [ ]:
print(torch.max(tensor1))
print(torch.min(tensor1))
print(torch.mean(tensor_range))
print(torch.sum(tensor1))

tensor(7, dtype=torch.int8)
tensor(7, dtype=torch.int8)
tensor(3.)
tensor(7)


In [ ]:
print(f"Tensor range is on device: {tensor_range.device}\nAnd the type is: {type(tensor_range)}")
print(f"Now the device is: {tensor_range.to('cuda').device}")
print(f"Putting it back on cpu: {tensor_range.cpu().device}")
print(f"Converting to a numpy ndarray: {type(tensor_range.numpy())}")

Tensor range is on device: cpu
And the type is: <class 'torch.Tensor'>
Now the device is: cuda:0
Putting it back on cpu: cpu
Converting to a numpy ndarray: <class 'numpy.ndarray'>


**Day-2**

In [ ]:
import torch
import numpy as np
import pandas as pd
matmul1 = torch.ones((3,2))
matmul2 = torch.rand((3,2))

In [ ]:
print(f"When we try to multiply incompatible shapes: {matmul1 @ matmul2}")

RuntimeError: ignored

In [ ]:
print(f"When we multiply compatible shapes: {matmul1 @ matmul2.T}")

When we multiply compatible shapes: tensor([[0.5818, 0.8149, 1.1182],
        [0.5818, 0.8149, 1.1182],
        [0.5818, 0.8149, 1.1182]])


In [ ]:
random1 = torch.arange(0,100,10).type(torch.float32)
random2 = torch.arange(1,100,11).type(torch.float32)

print("For the first tensor:\n",random1.shape,random1.dtype,random1.device,random1.requires_grad)
print(f"Max: {torch.max(random1)}\nMin: {torch.min(random1)}\nMean: {torch.mean(random1)}\nSum: {torch.sum(random1)}")

print("Properties of second tensor:\n",random2.shape,random2.dtype,random2.device,random2.requires_grad)
print(f"Max: {torch.max(random2)}\nMin: {torch.min(random2)}\nMean: {torch.mean(random2)}\nSum: {torch.sum(random2)}")

For the first tensor:
 torch.Size([10]) torch.float32 cpu False
Max: 90.0
Min: 0.0
Mean: 45.0
Sum: 450.0
Properties of second tensor:
 torch.Size([9]) torch.float32 cpu False
Max: 89.0
Min: 1.0
Mean: 45.0
Sum: 405.0


In [ ]:
print(f"First tensor argmax: {torch.argmax(random1)}\nFirst tensor argmin {torch.argmin(random1)}")
print(f"Second tensor argmax: {torch.argmax(random2)}\nSecond tensor argmin: {torch.argmin(random2)}")

First tensor argmax: 9
First tensor argmin 0
Second tensor argmax: 8
Second tensor argmin: 0


In [ ]:
random3 = torch.rand(3,4).type(torch.float32)
print(random3.shape,random3.ndim)
random3_changed = random3.resize(2,6)
print(random3_changed.shape, random3.ndim)

torch.Size([3, 4]) 2
torch.Size([2, 6]) 2


/usr/local/lib/python3.10/dist-packages/torch/_tensor.py:775: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [ ]:
print(f"Using view: {random3_changed.view(3,4)}")

Using view: tensor([[0.8487, 0.5354, 0.9941, 0.3809],
        [0.9362, 0.4601, 0.9022, 0.8033],
        [0.6131, 0.8383, 0.6299, 0.0833]])


In [ ]:
random4 = torch.rand((1,4))
stacked_vert = torch.stack([random4,random4],dim=1)
print(f"Stacked vertically: {stacked_vert}\ndim: {stacked_vert.ndim}\nshape: {stacked_vert.shape}")

stacked_hori = torch.stack([random4,random4],dim=0)
print(f"Stacked vertically: {stacked_hori}\ndim: {stacked_hori.ndim}\nshape: {stacked_hori.shape}")

Stacked vertically: tensor([[[0.4505, 0.2481, 0.4784, 0.2379],
         [0.4505, 0.2481, 0.4784, 0.2379]]])
dim: 3
shape: torch.Size([1, 2, 4])
Stacked vertically: tensor([[[0.4505, 0.2481, 0.4784, 0.2379]],

        [[0.4505, 0.2481, 0.4784, 0.2379]]])
dim: 3
shape: torch.Size([2, 1, 4])


In [ ]:
print(f"Squeezing stacked verticaly: {stacked_vert.squeeze().shape}")
print(f"Unsqueezing stacked horizontally: {stacked_hori.unsqueeze(dim=1).shape}")

Squeezing stacked verticaly: torch.Size([2, 4])
Unsqueezing stacked horizontally: torch.Size([2, 1, 1, 4])


In [ ]:
print(f"Original: {stacked_hori.shape}\nTensor: {stacked_hori}")
permuted = stacked_hori.permute(0,2,1)
print(f"Permuted: {permuted.shape}\nPermuted tensor: {permuted}")
print(f"Original: {stacked_hori}")

Original: torch.Size([2, 1, 4])
Tensor: tensor([[[0.4505, 0.2481, 0.4784, 0.2379]],

        [[0.4505, 0.2481, 0.4784, 0.2379]]])
Permuted: torch.Size([2, 4, 1])
Permuted tensor: tensor([[[0.4505],
         [0.2481],
         [0.4784],
         [0.2379]],

        [[0.4505],
         [0.2481],
         [0.4784],
         [0.2379]]])
Original: tensor([[[0.4505, 0.2481, 0.4784, 0.2379]],

        [[0.4505, 0.2481, 0.4784, 0.2379]]])


In [ ]:
np_array = np.arange(1,100,1)
print(type(np_array))
tens = torch.from_numpy(np_array).type(torch.float32)
print(type(tens))
print(tens.device)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(tens.to(device).device)
print(f"Dtype of tensor: {tens.dtype}")

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
cpu
cuda:0
Dtype of tensor: torch.float32


In [ ]:
import torch
import torch.nn as nn
torch.manual_seed(42)
weights = 0.7
bias = 0.3
X=torch.arange(0,1,0.02).unsqueeze(dim=1)
y = weights*X+bias
print(X.shape, X.dtype, X.device)
print(X)

torch.Size([50, 1]) torch.float32 cpu
tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800],
        [0.2000],
        [0.2200],
        [0.2400],
        [0.2600],
        [0.2800],
        [0.3000],
        [0.3200],
        [0.3400],
        [0.3600],
        [0.3800],
        [0.4000],
        [0.4200],
        [0.4400],
        [0.4600],
        [0.4800],
        [0.5000],
        [0.5200],
        [0.5400],
        [0.5600],
        [0.5800],
        [0.6000],
        [0.6200],
        [0.6400],
        [0.6600],
        [0.6800],
        [0.7000],
        [0.7200],
        [0.7400],
        [0.7600],
        [0.7800],
        [0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800]])


In [ ]:
train_x = X[:int(0.8*len(X)),0]
train_y = y[:int(0.8*len(X)),0]

val_x = X[int(0.8*len(X)):50,0]
val_y = y[int(0.8*len(X)):50,0]
print(train_x, '\n', val_x)
print(len(train_x),len(train_y), '\n', len(val_x),len(val_y))

tensor([0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
        0.1800, 0.2000, 0.2200, 0.2400, 0.2600, 0.2800, 0.3000, 0.3200, 0.3400,
        0.3600, 0.3800, 0.4000, 0.4200, 0.4400, 0.4600, 0.4800, 0.5000, 0.5200,
        0.5400, 0.5600, 0.5800, 0.6000, 0.6200, 0.6400, 0.6600, 0.6800, 0.7000,
        0.7200, 0.7400, 0.7600, 0.7800]) 
 tensor([0.8000, 0.8200, 0.8400, 0.8600, 0.8800, 0.9000, 0.9200, 0.9400, 0.9600,
        0.9800])
40 40 
 10 10


In [ ]:
class model(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
    self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
    # self.linear1 = nn.Linear(inp, hidden1)

  def forward(self,x):
    z = self.weights*x+self.bias
    return z

In [ ]:
linear_regressor = model()

**Day-3**